#!/bin/bash

set -e

NEXUS_CONFIG_SCRIPTS=${NEXUS_CONFIG_SCRIPTS:-/nexusconfig}
NEXUS_CONFIG_TOUCHPOINT=${NEXUS_CONFIG_TOUCHPOINT:-/var/run/nexus-config-touchpoint}
NEXUS_CONFIG_DIR=${NEXUS_CONFIG_DIR:-/etc/nexus-config}

if [ -n "$NEXUS_CONFIG_TOUCHPOINT" -a ! -f "$NEXUS_CONFIG_TOUCHPOINT" ] ; then
    while ! curl -k --fail "$NEXUS_BASEURL/service/rest/v1/status" >/dev/null 2>&1 ; do
       echo "nexus-config: Waiting for Nexus start..."
       sleep 1
    done

    $NEXUS_CONFIG_SCRIPTS/uploadGroovyScript.sh createUser $NEXUS_CONFIG_SCRIPTS/createUser.groovy

    if [ -d "$NEXUS_CONFIG_DIR" ] ; then
      for u in $NEXUS_CONFIG_DIR/user.* ; do
         exec 3<"$u"
         read -r -u 3 USERNAME
         read -r -u 3 PASSWORD
         exec 3>&-

         if ! $NEXUS_CONFIG_SCRIPTS/runScript.sh createUser "$USERNAME" "$PASSWORD" ; then
             echo "nexus-config: Creation of user $USERNAME failed"
         else
             echo "nexus-config: Created user $USERNAME"
         fi
      done
    fi
    touch $NEXUS_CONFIG_TOUCHPOINT
fi

# block forever; dirty hack because we're launched by runit which manages 'services'
echo "nexus-config: sleeping forever..."
while true; do sleep 10000; done
