apiVersion: v1
appVersion: 3.23.0-03
description: Sonatype Nexus is an open source repository manager
home: https://www.sonatype.com/nexus-repository-oss
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
maintainers:
- name: Gregory.Cuny@fr.ibm.com
- name: Nicolas.Duboc@fr.ibm.com
name: devops-nexus
sources:
- https://github.com/sonatype/nexus-public
- https://github.com/travelaudience/docker-nexus
- https://github.com/travelaudience/kubernetes-nexus
- https://github.com/travelaudience/docker-nexus-backup
version: 0.2.0
