#!/bin/bash

set -e

GITEA_INIT_TOUCHPOINT=${GITEA_INIT_TOUCHPOINT:-/var/run/gitea-init-touchpoint}
GITEA_INIT_CONFIG_DIR=${GITEA_INIT_CONFIG_DIR:-/etc/gitea-init-config}

if [ -n "$GITEA_INIT_TOUCHPOINT" -a ! -f "$GITEA_INIT_TOUCHPOINT" ] ; then
    # wait for gitea web to have initialized the DB tables
    while ! gitea admin auth list >/dev/null 2>&1 ; do
       echo "gitea-config-service: Waiting for gitea start..."
       sleep 1
    done

    if [ -d "$GITEA_INIT_CONFIG_DIR" ] ; then
      for u in $GITEA_INIT_CONFIG_DIR/user.* ; do
         exec 3<"$u"
         read -r -u 3 USERNAME
         read -r -u 3 PASSWORD
         read -r -u 3 IS_ADMIN
         exec 3>&-

         if [ "admin" = "$IS_ADMIN" ] ; then
            IS_ADMIN="--admin"
         else
            IS_ADMIN=""
         fi

         su-exec $USER /app/gitea/gitea admin create-user \
              --name "$USERNAME" \
              --password "$PASSWORD" \
              $IS_ADMIN \
              --email "$USERNAME@example.com"
         echo "gitea-config-service: Created user $USERNAME"
      done
    fi
    #curl -v -u gitadmin:gitadmin -X POST -H "Content-Type: application/json" "http://localhost:3000/api/v1/admin/users/gitadmin/keys"  --data '{"title":"test", "key": "ssh-rsa AAA...VCsub foo@localhost"}'
    touch $GITEA_INIT_TOUCHPOINT
fi

# block forever; dirty hack because we're launched by S6 which manages 'services'
while true; do sleep 10000; done
