##
## Sample of values.yaml for deployment of the DevOps stack.
## See Readme.md for usage instructions.
##

devops-gitea:
  images:
    gitea:
      name: "ci-cd-stack/gitea"
      tag: "0.1.0"
    pullPolicy: Never  # because image pushed to Minikube internal registry are not downloadable

  ingress:
    tls: []

  service:
    http:
      externalHost: git.MINIKUBE_IP.nip.io
    ssh:
      externalHost: git.MINIKUBE_IP.nip.io

  persistence:
    giteaSize: 2Gi
    postgresSize: 2Gi
    storageClass: null   # use minikube PV provisioner


devops-nexus:
  nexus:
    imageName: ci-cd-stack/nexus
    imageTag: 0.2.1
    imagePullPolicy: Never # see gitea.images.pullPolicy above
    livenessProbe:
      failureThreshold: 10
    readinessProbe:
      failureThreshold: 10

  nexusProxy:
    env:
      nexusHttpHost: nexus.MINIKUBE_IP.nip.io

  ingress:
    tls:
      enabled: false

  persistence:
    storageClass: null   # use minikube PV provisioner
    storageSize: 6Gi

  nexusBackup:
    persistence:
      enabled: false

jenkins:
   master:
     ingress:
       hostName: jenkins.MINIKUBE_IP.nip.io
       tls: []
     nexusUrl: http://nexus.MINIKUBE_IP.nip.io

   persistence:
     enabled: true
     storageClass: null   # use minikube PV provisioner
     size: "2Gi"
