##
## Sample of values.yaml for deployment of the DevOps stack.
## See Readme.md for usage instructions.
##

devops-nexus:
  nexus:
    imageName: IMAGE_REGISTRY/PROJECT/nexus
    imageTag: 0.2.1
    livenessProbe:
      failureThreshold: 10
    readinessProbe:
      failureThreshold: 10

  nexusProxy:
    env:
      nexusHttpHost: NEXUS_HOST

  ingress:
    tls:
      enabled: true
      secretName: cicd-tls

  persistence:
    storageClass: null   # use default PV provisioner
    storageSize: 6Gi

  serviceAccount:
    create: false
    name: default

  nexusBackup:
    persistence:
      enabled: false

