{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "nexus.fullname" . }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
    {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- if .Values.nexusProxy.env.nexusHttpHost }}
    - host: {{ .Values.nexusProxy.env.nexusHttpHost }}
      http:
        paths:
          - backend:
              service:
            {{- if .Values.nexusProxy.svcName }}
                name: {{ .Values.nexusProxy.svcName }}
            {{- else }}
                name: {{ template "nexus.fullname" . }}
            {{- end }}
                port:
{{- if .Values.nexusProxy.enabled }}
                  number: {{ .Values.nexusProxy.port }}
{{- else }}
                  number: {{ .Values.nexus.nexusPort }}
{{- end }}
            path: {{ .Values.ingress.path }}
            pathType: Prefix
{{- end }}
{{- if .Values.nexusProxy.enabled -}}
  {{- if .Values.nexusProxy.env.nexusDockerHost }}
    - host: {{ .Values.nexusProxy.env.nexusDockerHost }}
      http:
        paths:
          - backend:
              service:
            {{- if .Values.nexusProxy.svcName }}
                name: {{ .Values.nexusProxy.svcName }}
            {{- else }}
                name: {{ template "nexus.fullname" . }}
            {{- end }}
                port: 
                  number: {{ .Values.nexusProxy.port }}
            path: {{ .Values.ingress.path }}
            pathType: Prefix
  {{- end }}
{{- end -}}
  {{- with .Values.ingress.rules }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- if .Values.nexusProxy.env.nexusHttpHost }}
        - {{ .Values.nexusProxy.env.nexusHttpHost }}
      {{- end }}
      {{- if .Values.nexusProxy.env.nexusDockerHost }}
        - {{ .Values.nexusProxy.env.nexusDockerHost }}
      {{- end }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
      {{- end }}
{{- end -}}
{{- end }}
