apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.fullname" . }}-init-conf
  labels:
{{ include "nexus.labels" . | indent 4 }}
{{- if .Values.nexus.labels }}
{{ toYaml .Values.nexus.labels | indent 4 }}
{{- end }}
data:
{{- range $index, $user := .Values.nexus.config.users }}
  user.{{ $index }}: |
      {{ $user.username }}
      {{ $user.password }}
{{- end }}
