appVersion: 1.6.1
description: Git with a cup of tea
icon: https://docs.gitea.io/images/gitea.png
keywords:
- git
- issue tracker
- code review
- wiki
- gitea
- gogs
maintainers:
- name: Nicolas.Duboc@fr.ibm.com
name: devops-gitea
sources:
- https://github.com/go-gitea/gitea
- https://hub.docker.com/r/gitea/gitea/
version: 0.2.0
